-- ============================================================
-- Migration 003: AI Caption Tracking Fields
--
-- Adds columns to portfolio_images to track which images have
-- AI-generated metadata, when they were generated, and what
-- SEO keywords were used in the generation prompt.
-- ============================================================

ALTER TABLE portfolio_images
  ADD COLUMN IF NOT EXISTS ai_generated    BOOLEAN     NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ai_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS seo_keywords    TEXT        NOT NULL DEFAULT '';

-- Backfill: mark any image that already has non-empty alt_en as ai_generated
-- (conservative — only set if both alt_en and alt_es are populated,
--  which indicates the localized migration has been applied)
UPDATE portfolio_images
SET    ai_generated = false  -- leave as-is until user explicitly generates
WHERE  ai_generated = false;

-- Index for admin queries: "show me images without AI captions"
CREATE INDEX IF NOT EXISTS idx_portfolio_images_ai_generated
  ON portfolio_images (ai_generated);

COMMENT ON COLUMN portfolio_images.ai_generated    IS 'true if alt/caption were generated by GPT-4o Vision';
COMMENT ON COLUMN portfolio_images.ai_generated_at IS 'timestamp of the last AI generation run';
COMMENT ON COLUMN portfolio_images.seo_keywords    IS 'page-level keywords injected into the AI prompt during last generation';
